id: P004592
initial_creation_type: ocr
source_metadata:
  id: bdr:W1PD45098
  title: གངས་རྒྱན་མེ་ཏོག
  author: ''
  volumes:
    db0eade8eb0a43ab9303cd4d40bfaeef:
      image_group_id: I2DB57012
      title: ''
      volume_number: 1
      total_pages: 102
    48bdde32752344649150606a67a447a8:
      image_group_id: I2DB57013
      title: ''
      volume_number: 2
      total_pages: 0
    063b5f898e54479da70564038b26cfc1:
      image_group_id: I2DB57014
      title: ''
      volume_number: 3
      total_pages: 102
    4113fb0004ef464594a746d30f6dd1a3:
      image_group_id: I2DB57015
      title: ''
      volume_number: 4
      total_pages: 90
    8ef36ebf33d94d7d8532af3a515e10b5:
      image_group_id: I2DB57016
      title: ''
      volume_number: 5
      total_pages: 78
    28db0de0bb884386a6ac39ca5d51d5d6:
      image_group_id: I2DB57017
      title: ''
      volume_number: 6
      total_pages: 90
    7bca277d8cee41ba86702f5939989b4e:
      image_group_id: I2DB57018
      title: ''
      volume_number: 7
      total_pages: 82
    d139e7a5ca3847ee93f83a8ce1bb4141:
      image_group_id: I2DB57019
      title: ''
      volume_number: 8
      total_pages: 78
    22d51c92e403426da9741633b0a76f8a:
      image_group_id: I2DB57020
      title: ''
      volume_number: 9
      total_pages: 82
    605aa555c94840bda3a77d83cacc41ee:
      image_group_id: I2DB57021
      title: ''
      volume_number: 10
      total_pages: 78
    6694e323f65f45f58184e0e8525a493a:
      image_group_id: I2DB57022
      title: ''
      volume_number: 11
      total_pages: 90
    fd804ea0da6f4e7d9095d42f1028e548:
      image_group_id: I2DB57023
      title: ''
      volume_number: 12
      total_pages: 82
    33b1a0149a1c4d0c87a57a992405560e:
      image_group_id: I2DB57024
      title: ''
      volume_number: 13
      total_pages: 78
    16b6cefaa2f54530bd9e70de34283be5:
      image_group_id: I2DB57025
      title: ''
      volume_number: 14
      total_pages: 78
    c57b1c8bbaef4f58987006d23be13eca:
      image_group_id: I2DB57026
      title: ''
      volume_number: 15
      total_pages: 78
    8572853a0b524e01aa5b49f27400335c:
      image_group_id: I2DB57027
      title: ''
      volume_number: 16
      total_pages: 86
    074bfccb2def41238dff0c46c4a6c4e1:
      image_group_id: I2DB57028
      title: ''
      volume_number: 17
      total_pages: 82
    bf5f5b65db9643c28c6de4e176a126f4:
      image_group_id: I2DB57029
      title: ''
      volume_number: 18
      total_pages: 82
    c58730ad6b6042a4aec9d6243b8c9643:
      image_group_id: I2DB57030
      title: ''
      volume_number: 19
      total_pages: 78
    f318fb4bcb754ae8957a30a4af5d2a05:
      image_group_id: I2DB57031
      title: ''
      volume_number: 20
      total_pages: 0
    1c40cc18d3034b1a8e8dc2bc6fe6bd71:
      image_group_id: I2DB57032
      title: ''
      volume_number: 21
      total_pages: 82
    fca42686ee23489288ca4b5ee4c0e0ce:
      image_group_id: I2DB57033
      title: ''
      volume_number: 22
      total_pages: 74
    5616f923d59a41e7a948fbba9b232cd1:
      image_group_id: I2DB57034
      title: ''
      volume_number: 23
      total_pages: 94
    ec7788a2f9674e288e77bce0d7428ded:
      image_group_id: I2DB57035
      title: ''
      volume_number: 24
      total_pages: 94
    b24d40cfb5da409f9efe3865f818c4ab:
      image_group_id: I2DB57036
      title: ''
      volume_number: 25
      total_pages: 76
    f0020191fedd48818c68e36299d78a3b:
      image_group_id: I2DB57037
      title: ''
      volume_number: 26
      total_pages: 82
    76ac078b7d5a48a58e083a7016cb732b:
      image_group_id: I2DB57038
      title: ''
      volume_number: 27
      total_pages: 78
    e92914777de0436d853469e8eccf8080:
      image_group_id: I2DB57039
      title: ''
      volume_number: 28
      total_pages: 78
    145cfc9881254584bc64ff95f6a1cd85:
      image_group_id: I2DB57040
      title: ''
      volume_number: 29
      total_pages: 70
    47978e20292f487eacf9cbcae5429cad:
      image_group_id: I2DB57041
      title: ''
      volume_number: 30
      total_pages: 84
    8792e7a558fb470eb45b4289a12219df:
      image_group_id: I2DB57042
      title: ''
      volume_number: 31
      total_pages: 70
    13aaf9821b47478c818f816eb59052c7:
      image_group_id: I2DB57043
      title: ''
      volume_number: 32
      total_pages: 66
    8e1259b6a70847feabe22f0b512a92f0:
      image_group_id: I2DB57044
      title: ''
      volume_number: 33
      total_pages: 70
    8e318aa485834fb7bbee3ad36f8a1209:
      image_group_id: I2DB57045
      title: ''
      volume_number: 34
      total_pages: 66
    9e4912f22d94487085d9e00a53707df8:
      image_group_id: I2DB57046
      title: ''
      volume_number: 35
      total_pages: 66
    7bdd80599b744f7898b2bad0936771a0:
      image_group_id: I2DB57047
      title: ''
      volume_number: 36
      total_pages: 70
    895b545fd6784b0a8e39ed2c657bfd43:
      image_group_id: I2DB57048
      title: ''
      volume_number: 37
      total_pages: 70
    42ccf51ea8a643d1a8619fe92f890d31:
      image_group_id: I2DB57049
      title: ''
      volume_number: 38
      total_pages: 70
    a7d9a8726ed24bf9b83631fd5fc69a9e:
      image_group_id: I2DB57050
      title: ''
      volume_number: 39
      total_pages: 66
    328b1b3cbfc64e759bfe46610809a05e:
      image_group_id: I2DB57051
      title: ''
      volume_number: 40
      total_pages: 70
    eb1391cbb7d94264bdf7cd7e91db8307:
      image_group_id: I2DB57052
      title: ''
      volume_number: 41
      total_pages: 70
    a5594d2a5c314287943f5c70d1d8e0c5:
      image_group_id: I2DB57053
      title: ''
      volume_number: 42
      total_pages: 86
    0c959c8145654e08b94c099b42262c3c:
      image_group_id: I2DB57054
      title: ''
      volume_number: 43
      total_pages: 86
    b0f9bf9d3312430283e018d20a20f13b:
      image_group_id: I2DB57055
      title: ''
      volume_number: 44
      total_pages: 90
    c9a791d472544eb6bd0846badeaf70a5:
      image_group_id: I2DB57056
      title: ''
      volume_number: 45
      total_pages: 86
    de7e7d55e41645019017fb0a85e3114f:
      image_group_id: I2DB57057
      title: ''
      volume_number: 46
      total_pages: 90
    3366385dd86c4ec5b7cbf9f34ae8fe65:
      image_group_id: I2DB57058
      title: ''
      volume_number: 47
      total_pages: 90
    8aa790f6e8f34537a6605964dc5c330f:
      image_group_id: I2DB57059
      title: ''
      volume_number: 48
      total_pages: 86
    0819bc5df78b4c4a9129b7111fb4c424:
      image_group_id: I2DB57060
      title: ''
      volume_number: 49
      total_pages: 90
    294307ede1c64b3895e22c150c71f048:
      image_group_id: I2DB57061
      title: ''
      volume_number: 50
      total_pages: 90
    38cd4153df634e658ecfc3a531d296e1:
      image_group_id: I2DB57062
      title: ''
      volume_number: 51
      total_pages: 90
    8a7ace03404542c59a1fcaa7a2b57f86:
      image_group_id: I2DB57063
      title: ''
      volume_number: 52
      total_pages: 90
    5ea9e2baba3946f4850fc54119387b31:
      image_group_id: I2DB57064
      title: ''
      volume_number: 53
      total_pages: 86
    07058ea12d864b4ebea09ff64cdd5c0d:
      image_group_id: I2DB57065
      title: ''
      volume_number: 54
      total_pages: 90
    638a7d23394143ae84d0a0e85d65b381:
      image_group_id: I2DB57066
      title: ''
      volume_number: 55
      total_pages: 90
    a6442eeb47e44e78bc74d7aa66bc52bc:
      image_group_id: I2DB57067
      title: ''
      volume_number: 56
      total_pages: 0
    32ed1d59682f496f8996608f2db38a62:
      image_group_id: I2DB57068
      title: ''
      volume_number: 57
      total_pages: 0
    3de7fa7241cd457ab56220b7942cfa69:
      image_group_id: I2DB57069
      title: ''
      volume_number: 58
      total_pages: 0
    a1fa92003b3c4aaa873a2369b5b12708:
      image_group_id: I2DB57070
      title: ''
      volume_number: 59
      total_pages: 0
    fae508b94073491fb45cd9311726cbe8:
      image_group_id: I2DB57071
      title: ''
      volume_number: 60
      total_pages: 90
    44d3903b4c9a4a708e2267499d0be682:
      image_group_id: I2DB57072
      title: ''
      volume_number: 61
      total_pages: 0
    37e5bbbebd0b4e9fa6a7cca1259685e5:
      image_group_id: I2DB57073
      title: ''
      volume_number: 62
      total_pages: 90
    09f65ea4ffd7449cbbc10e760cb6b2d1:
      image_group_id: I2DB57074
      title: ''
      volume_number: 63
      total_pages: 0
    b911d29c415f4cdfb4f8ae8cb446712d:
      image_group_id: I2DB57075
      title: ''
      volume_number: 64
      total_pages: 0
    827933e865b344b1b83c79ec44e757fe:
      image_group_id: I2DB57076
      title: ''
      volume_number: 65
      total_pages: 0
    6a66dd1b97484b17b2ec6ae32d936a7e:
      image_group_id: I2DB57077
      title: ''
      volume_number: 66
      total_pages: 0
    0a203eb2f51d433f9f1d3328e8cf39e4:
      image_group_id: I2DB57078
      title: ''
      volume_number: 67
      total_pages: 0
    19601b3d04c0423f943688ac5eb20789:
      image_group_id: I2DB57079
      title: ''
      volume_number: 68
      total_pages: 0
    2789efbed2fe423e8bef8715fc36d3fe:
      image_group_id: I2DB57080
      title: ''
      volume_number: 69
      total_pages: 0
    32a868e8d3a94bcfba3764e8d2ee3228:
      image_group_id: I2DB57081
      title: ''
      volume_number: 70
      total_pages: 0
    e9ad8f9b6faa41da841415a8c3db9a9c:
      image_group_id: I2DB57082
      title: ''
      volume_number: 71
      total_pages: 0
    6495569df23440d2977fd62f301dded8:
      image_group_id: I2DB57083
      title: ''
      volume_number: 72
      total_pages: 0
    b1231bd372fe45c8b7a433b5890391f1:
      image_group_id: I2DB57084
      title: ''
      volume_number: 73
      total_pages: 0
    8e0ed85280ef43f9b5c44db5c2ba07b1:
      image_group_id: I2DB57085
      title: ''
      volume_number: 74
      total_pages: 0
    ec7d5724cad74ddb866e8083d5b99bb4:
      image_group_id: I2DB57086
      title: ''
      volume_number: 75
      total_pages: 0
