id: IB9FF9144
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T19:59:00+00:00'
last_modified: '2022-06-08T02:10:09.339348+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1PD45098
  title: གངས་རྒྱན་མེ་ཏོག
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    A9AC:
      image_group_id: I2DB57012
      title: ''
      total_pages: 102
      order: 1
      base_file: A9AC.txt
    A93D:
      image_group_id: I2DB57013
      title: ''
      total_pages: 0
      order: 2
      base_file: A93D.txt
    F77A:
      image_group_id: I2DB57014
      title: ''
      total_pages: 102
      order: 3
      base_file: F77A.txt
    E92B:
      image_group_id: I2DB57015
      title: ''
      total_pages: 90
      order: 4
      base_file: E92B.txt
    D033:
      image_group_id: I2DB57016
      title: ''
      total_pages: 78
      order: 5
      base_file: D033.txt
    49A1:
      image_group_id: I2DB57017
      title: ''
      total_pages: 90
      order: 6
      base_file: 49A1.txt
    420A:
      image_group_id: I2DB57018
      title: ''
      total_pages: 82
      order: 7
      base_file: 420A.txt
    1DA6:
      image_group_id: I2DB57019
      title: ''
      total_pages: 78
      order: 8
      base_file: 1DA6.txt
    '6704':
      image_group_id: I2DB57020
      title: ''
      total_pages: 82
      order: 9
      base_file: 6704.txt
    ECEF:
      image_group_id: I2DB57021
      title: ''
      total_pages: 78
      order: 10
      base_file: ECEF.txt
    '3474':
      image_group_id: I2DB57022
      title: ''
      total_pages: 90
      order: 11
      base_file: 3474.txt
    A51F:
      image_group_id: I2DB57023
      title: ''
      total_pages: 82
      order: 12
      base_file: A51F.txt
    F52F:
      image_group_id: I2DB57024
      title: ''
      total_pages: 78
      order: 13
      base_file: F52F.txt
    C0A4:
      image_group_id: I2DB57025
      title: ''
      total_pages: 78
      order: 14
      base_file: C0A4.txt
    46E7:
      image_group_id: I2DB57026
      title: ''
      total_pages: 78
      order: 15
      base_file: 46E7.txt
    '1568':
      image_group_id: I2DB57027
      title: ''
      total_pages: 86
      order: 16
      base_file: 1568.txt
    DB6F:
      image_group_id: I2DB57028
      title: ''
      total_pages: 82
      order: 17
      base_file: DB6F.txt
    E3ED:
      image_group_id: I2DB57029
      title: ''
      total_pages: 82
      order: 18
      base_file: E3ED.txt
    3AF2:
      image_group_id: I2DB57030
      title: ''
      total_pages: 78
      order: 19
      base_file: 3AF2.txt
    AD08:
      image_group_id: I2DB57031
      title: ''
      total_pages: 0
      order: 20
      base_file: AD08.txt
    C3A2:
      image_group_id: I2DB57032
      title: ''
      total_pages: 82
      order: 21
      base_file: C3A2.txt
    CCA8:
      image_group_id: I2DB57033
      title: ''
      total_pages: 74
      order: 22
      base_file: CCA8.txt
    '5444':
      image_group_id: I2DB57034
      title: ''
      total_pages: 94
      order: 23
      base_file: 5444.txt
    940D:
      image_group_id: I2DB57035
      title: ''
      total_pages: 94
      order: 24
      base_file: 940D.txt
    525E:
      image_group_id: I2DB57036
      title: ''
      total_pages: 76
      order: 25
      base_file: 525E.txt
    '4443':
      image_group_id: I2DB57037
      title: ''
      total_pages: 82
      order: 26
      base_file: 4443.txt
    '1073':
      image_group_id: I2DB57038
      title: ''
      total_pages: 78
      order: 27
      base_file: 1073.txt
    314C:
      image_group_id: I2DB57039
      title: ''
      total_pages: 78
      order: 28
      base_file: 314C.txt
    2FE2:
      image_group_id: I2DB57040
      title: ''
      total_pages: 70
      order: 29
      base_file: 2FE2.txt
    70B5:
      image_group_id: I2DB57041
      title: ''
      total_pages: 84
      order: 30
      base_file: 70B5.txt
    6D0A:
      image_group_id: I2DB57042
      title: ''
      total_pages: 70
      order: 31
      base_file: 6D0A.txt
    B918:
      image_group_id: I2DB57043
      title: ''
      total_pages: 66
      order: 32
      base_file: B918.txt
    151C:
      image_group_id: I2DB57044
      title: ''
      total_pages: 70
      order: 33
      base_file: 151C.txt
    7A4E:
      image_group_id: I2DB57045
      title: ''
      total_pages: 66
      order: 34
      base_file: 7A4E.txt
    0584:
      image_group_id: I2DB57046
      title: ''
      total_pages: 66
      order: 35
      base_file: 0584.txt
    CD8A:
      image_group_id: I2DB57047
      title: ''
      total_pages: 70
      order: 36
      base_file: CD8A.txt
    '3037':
      image_group_id: I2DB57048
      title: ''
      total_pages: 70
      order: 37
      base_file: 3037.txt
    CDD5:
      image_group_id: I2DB57049
      title: ''
      total_pages: 70
      order: 38
      base_file: CDD5.txt
    EAD0:
      image_group_id: I2DB57050
      title: ''
      total_pages: 66
      order: 39
      base_file: EAD0.txt
    399F:
      image_group_id: I2DB57051
      title: ''
      total_pages: 70
      order: 40
      base_file: 399F.txt
    B044:
      image_group_id: I2DB57052
      title: ''
      total_pages: 70
      order: 41
      base_file: B044.txt
    '9768':
      image_group_id: I2DB57053
      title: ''
      total_pages: 86
      order: 42
      base_file: 9768.txt
    '1633':
      image_group_id: I2DB57054
      title: ''
      total_pages: 86
      order: 43
      base_file: 1633.txt
    8D37:
      image_group_id: I2DB57055
      title: ''
      total_pages: 90
      order: 44
      base_file: 8D37.txt
    B505:
      image_group_id: I2DB57056
      title: ''
      total_pages: 86
      order: 45
      base_file: B505.txt
    8C54:
      image_group_id: I2DB57057
      title: ''
      total_pages: 90
      order: 46
      base_file: 8C54.txt
    99FF:
      image_group_id: I2DB57058
      title: ''
      total_pages: 90
      order: 47
      base_file: 99FF.txt
    '1234':
      image_group_id: I2DB57059
      title: ''
      total_pages: 86
      order: 48
      base_file: 1234.txt
    '2653':
      image_group_id: I2DB57060
      title: ''
      total_pages: 90
      order: 49
      base_file: 2653.txt
    B545:
      image_group_id: I2DB57061
      title: ''
      total_pages: 90
      order: 50
      base_file: B545.txt
    250C:
      image_group_id: I2DB57062
      title: ''
      total_pages: 90
      order: 51
      base_file: 250C.txt
    '5755':
      image_group_id: I2DB57063
      title: ''
      total_pages: 90
      order: 52
      base_file: 5755.txt
    '1941':
      image_group_id: I2DB57064
      title: ''
      total_pages: 86
      order: 53
      base_file: 1941.txt
    '2323':
      image_group_id: I2DB57065
      title: ''
      total_pages: 90
      order: 54
      base_file: 2323.txt
    17C5:
      image_group_id: I2DB57066
      title: ''
      total_pages: 90
      order: 55
      base_file: 17C5.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
